set SynModuleInfo {
  {SRCNAME apply_bit_reverse MODELNAME apply_bit_reverse RTLNAME Crypto_apply_bit_reverse
    SUBMODULES {
      {MODELNAME Crypto_flow_control_loop_pipe_sequential_init RTLNAME Crypto_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME Crypto_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_210_8 MODELNAME Crypto_Pipeline_VITIS_LOOP_210_8 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_210_8}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_210_83 MODELNAME Crypto_Pipeline_VITIS_LOOP_210_83 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_210_83}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_210_84 MODELNAME Crypto_Pipeline_VITIS_LOOP_210_84 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_210_84}
  {SRCNAME MUL_MOD MODELNAME MUL_MOD RTLNAME Crypto_MUL_MOD
    SUBMODULES {
      {MODELNAME Crypto_mul_16ns_16ns_32_1_0 RTLNAME Crypto_mul_16ns_16ns_32_1_0 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME Crypto_mux_3_2_20_1_0 RTLNAME Crypto_mux_3_2_20_1_0 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME Crypto_mux_3_2_31_1_0 RTLNAME Crypto_mux_3_2_31_1_0 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME Crypto_mul_15ns_16ns_31_1_0 RTLNAME Crypto_mul_15ns_16ns_31_1_0 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME Crypto_mac_muladd_16ns_16ns_32ns_33_4_0 RTLNAME Crypto_mac_muladd_16ns_16ns_32ns_33_4_0 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME Crypto_mac_muladd_16ns_15ns_32ns_33_4_0 RTLNAME Crypto_mac_muladd_16ns_15ns_32ns_33_4_0 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME ADD_MOD MODELNAME ADD_MOD RTLNAME Crypto_ADD_MOD}
  {SRCNAME SUB_MOD MODELNAME SUB_MOD RTLNAME Crypto_SUB_MOD}
  {SRCNAME Crypto_Pipeline_INTT_PE_LOOP MODELNAME Crypto_Pipeline_INTT_PE_LOOP RTLNAME Crypto_Crypto_Pipeline_INTT_PE_LOOP
    SUBMODULES {
      {MODELNAME Crypto_mux_4_2_32_1_1 RTLNAME Crypto_mux_4_2_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME Crypto_mul_11s_11s_11_1_1 RTLNAME Crypto_mul_11s_11s_11_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Crypto_Pipeline_INTT_PE_LOOP5 MODELNAME Crypto_Pipeline_INTT_PE_LOOP5 RTLNAME Crypto_Crypto_Pipeline_INTT_PE_LOOP5}
  {SRCNAME Crypto_Pipeline_INTT_PE_LOOP6 MODELNAME Crypto_Pipeline_INTT_PE_LOOP6 RTLNAME Crypto_Crypto_Pipeline_INTT_PE_LOOP6}
  {SRCNAME Crypto_Pipeline_MUL_INV_LOOP MODELNAME Crypto_Pipeline_MUL_INV_LOOP RTLNAME Crypto_Crypto_Pipeline_MUL_INV_LOOP}
  {SRCNAME Crypto_Pipeline_MUL_INV_LOOP21 MODELNAME Crypto_Pipeline_MUL_INV_LOOP21 RTLNAME Crypto_Crypto_Pipeline_MUL_INV_LOOP21}
  {SRCNAME Crypto_Pipeline_MUL_INV_LOOP22 MODELNAME Crypto_Pipeline_MUL_INV_LOOP22 RTLNAME Crypto_Crypto_Pipeline_MUL_INV_LOOP22}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_165_5 MODELNAME Crypto_Pipeline_VITIS_LOOP_165_5 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_165_5}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_165_51 MODELNAME Crypto_Pipeline_VITIS_LOOP_165_51 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_165_51}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_165_52 MODELNAME Crypto_Pipeline_VITIS_LOOP_165_52 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_165_52}
  {SRCNAME Crypto_Pipeline_NTT_PE_LOOP MODELNAME Crypto_Pipeline_NTT_PE_LOOP RTLNAME Crypto_Crypto_Pipeline_NTT_PE_LOOP}
  {SRCNAME Crypto_Pipeline_NTT_PE_LOOP19 MODELNAME Crypto_Pipeline_NTT_PE_LOOP19 RTLNAME Crypto_Crypto_Pipeline_NTT_PE_LOOP19}
  {SRCNAME Crypto_Pipeline_NTT_PE_LOOP20 MODELNAME Crypto_Pipeline_NTT_PE_LOOP20 RTLNAME Crypto_Crypto_Pipeline_NTT_PE_LOOP20}
  {SRCNAME MUL_MOD.1 MODELNAME MUL_MOD_1 RTLNAME Crypto_MUL_MOD_1}
  {SRCNAME Crypto_Pipeline_POLY_MUL_LOOP MODELNAME Crypto_Pipeline_POLY_MUL_LOOP RTLNAME Crypto_Crypto_Pipeline_POLY_MUL_LOOP}
  {SRCNAME Crypto_Pipeline_POLY_MUL_LOOP23 MODELNAME Crypto_Pipeline_POLY_MUL_LOOP23 RTLNAME Crypto_Crypto_Pipeline_POLY_MUL_LOOP23}
  {SRCNAME Crypto_Pipeline_POLY_MUL_LOOP24 MODELNAME Crypto_Pipeline_POLY_MUL_LOOP24 RTLNAME Crypto_Crypto_Pipeline_POLY_MUL_LOOP24}
  {SRCNAME Crypto_Pipeline_POLY_SUB_LOOP MODELNAME Crypto_Pipeline_POLY_SUB_LOOP RTLNAME Crypto_Crypto_Pipeline_POLY_SUB_LOOP}
  {SRCNAME Crypto_Pipeline_POLY_SUB_LOOP17 MODELNAME Crypto_Pipeline_POLY_SUB_LOOP17 RTLNAME Crypto_Crypto_Pipeline_POLY_SUB_LOOP17}
  {SRCNAME Crypto_Pipeline_POLY_SUB_LOOP18 MODELNAME Crypto_Pipeline_POLY_SUB_LOOP18 RTLNAME Crypto_Crypto_Pipeline_POLY_SUB_LOOP18}
  {SRCNAME Crypto_Pipeline_POLY_ADD_LOOP MODELNAME Crypto_Pipeline_POLY_ADD_LOOP RTLNAME Crypto_Crypto_Pipeline_POLY_ADD_LOOP}
  {SRCNAME Crypto_Pipeline_POLY_ADD_LOOP15 MODELNAME Crypto_Pipeline_POLY_ADD_LOOP15 RTLNAME Crypto_Crypto_Pipeline_POLY_ADD_LOOP15}
  {SRCNAME Crypto_Pipeline_POLY_ADD_LOOP16 MODELNAME Crypto_Pipeline_POLY_ADD_LOOP16 RTLNAME Crypto_Crypto_Pipeline_POLY_ADD_LOOP16}
  {SRCNAME MOD_PLAINTEXTMODULUS MODELNAME MOD_PLAINTEXTMODULUS RTLNAME Crypto_MOD_PLAINTEXTMODULUS}
  {SRCNAME Crypto_Pipeline_POLY_MOD_MODULUS_LOOP1 MODELNAME Crypto_Pipeline_POLY_MOD_MODULUS_LOOP1 RTLNAME Crypto_Crypto_Pipeline_POLY_MOD_MODULUS_LOOP1}
  {SRCNAME Crypto_Pipeline_POLY_MOD_MODULUS_LOOP113 MODELNAME Crypto_Pipeline_POLY_MOD_MODULUS_LOOP113 RTLNAME Crypto_Crypto_Pipeline_POLY_MOD_MODULUS_LOOP113}
  {SRCNAME Crypto_Pipeline_POLY_MOD_MODULUS_LOOP114 MODELNAME Crypto_Pipeline_POLY_MOD_MODULUS_LOOP114 RTLNAME Crypto_Crypto_Pipeline_POLY_MOD_MODULUS_LOOP114}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_83_3 MODELNAME Crypto_Pipeline_VITIS_LOOP_83_3 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_83_3}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_83_311 MODELNAME Crypto_Pipeline_VITIS_LOOP_83_311 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_83_311}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_83_312 MODELNAME Crypto_Pipeline_VITIS_LOOP_83_312 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_83_312}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_72_2 MODELNAME Crypto_Pipeline_VITIS_LOOP_72_2 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_72_2}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_72_29 MODELNAME Crypto_Pipeline_VITIS_LOOP_72_29 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_72_29}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_72_210 MODELNAME Crypto_Pipeline_VITIS_LOOP_72_210 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_72_210}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_61_1 MODELNAME Crypto_Pipeline_VITIS_LOOP_61_1 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_61_1}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_61_17 MODELNAME Crypto_Pipeline_VITIS_LOOP_61_17 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_61_17}
  {SRCNAME Crypto_Pipeline_VITIS_LOOP_61_18 MODELNAME Crypto_Pipeline_VITIS_LOOP_61_18 RTLNAME Crypto_Crypto_Pipeline_VITIS_LOOP_61_18}
  {SRCNAME Crypto MODELNAME Crypto RTLNAME Crypto IS_TOP 1
    SUBMODULES {
      {MODELNAME Crypto_sdiv_15ns_32s_11_19_seq_1 RTLNAME Crypto_sdiv_15ns_32s_11_19_seq_1 BINDTYPE op TYPE sdiv IMPL auto_seq LATENCY 18 ALLOW_PRAGMA 1}
      {MODELNAME Crypto_DataRAM_RAM_AUTO_1R1W RTLNAME Crypto_DataRAM_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME Crypto_BitReverseData_RAM_AUTO_1R1W RTLNAME Crypto_BitReverseData_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME Crypto_NTTTWiddleRAM_RAM_1WNR_AUTO_1R1W RTLNAME Crypto_NTTTWiddleRAM_RAM_1WNR_AUTO_1R1W BINDTYPE storage TYPE ram_1wnr IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME Crypto_control_s_axi RTLNAME Crypto_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
